### ISSUE TITLE
Migrate the JavaScript code to TypeScript

### ISSUE THREAD

**Issue by ErezBiren** [Xcov19/mycovidconnect#208]
**Is your feature request related to a problem? Please describe.**
no.

**Describe the solution you'd like**
migrating the JavaScript code to TypeScript.

**Describe alternatives you've considered**
Leave it as is.

**Additional context**
I would love to do this task.

**Comment by codecakes** [comment]
I like the idea of concise type correctness but I'd leave the syntax in JS and not TS because it is easier to pick up and understand for the larger OSS team working on this project and stress on type annotations and expanding test coverage instead;
See things like these: https://github.com/Xcov19/mycovidconnect/blob/887d71e68b8f22b6fd30bcce8e24b4122d86b55b/src/firebase/fireStore.js#L28

**Comment by ErezBiren** [comment]
When large coding projects have many developers, there is a chance of messier coding.
And number of errors increases which make the handling difficult. So type safety has feature to detect errors during coding time.

**Comment by codecakes** [comment]
> And number of errors increases which make the handling difficult. So type safety has feature to detect errors during coding time.
Is the sentiment ive echo'd in my previous comment with the existing caveat. I'd emphasize on Maintainability, Test coverage, reviews & good design as best practices here.

**Comment by ErezBiren** [comment]
great. 
Thanks for your time.
