### ISSUE TITLE
Implement a react form. openapi mock server available

### ISSUE THREAD

**Issue by codecakes** [Xcov19/mycovidconnect#233]
Implement a responsive 1 page react form with the existing site layout.

The website frontend repo can be run using its docker images on the local.
There is a working openapi doc to refer to which should make it easy to implement & test the endpoints out and implement the form. 
Documentation for development and testing with the mock server: https://mycovidconnect.stoplight.io/docs/registrations

**Additional context**
UI mock available. To be added here. remind me here if it's not.

**Comment by jayeclark** [comment]
@codecakes I'd like to help with this if this is open to new contributors. Tag me when you add the UI mock please!

**Comment by codecakes** [comment]
> @codecakes I'd like to help with this if this is open to new contributors. Tag me when you add the UI mock please!

@jayeclark Welcome! Go ahead and raise a PR! The resolution sizes are provided; 
Rename it to just .xd and drop the .zip (its for upload purpose only)
For quick preview you can try psdetch online tool;
[Covid Web Form.xd.zip](https://github.com/Xcov19/mycovidconnect/files/7652961/Covid.Web.Form.xd.zip)

Only treat this form as independent form; the rest of the layout for now (including header and footer) stays the same as is in the repo; Let me know if you face issues while running it on the local as per instructions in [ReadMe](https://github.com/Xcov19/mycovidconnect#install-docker-compose-on-mac) in which case, you should also feel free to raise another PR to add to the documentation what's missing!

**Comment by jayeclark** [comment]
Thanks, I’m not at my PC now but I will take a look in the morning and come back with any questions/clarifications!

**Comment by jayeclark** [comment]
@codecakes So sorry, but I'm not going to be able to work on this - the task is straightforward enough, but on attempting to follow the instructions to set up my local development environment I'm getting an assortment of errors related to missing files and irresolvable peer dependencies that I haven't ever even seen before. This is probably best handled by someone a little more experienced in ops troubleshooting.

**Comment by codecakes** [comment]
> @codecakes So sorry, but I'm not going to be able to work on this - the task is straightforward enough, but on attempting to follow the instructions to set up my local development environment I'm getting an assortment of errors related to missing files and irresolvable peer dependencies that I haven't ever even seen before. This is probably best handled by someone a little more experienced in ops troubleshooting.

@jayeclark Feel free to raise an issue and describe the steps there you followed so it becomes clear what are the issues and others can benefit from it.

**Comment by jayeclark** [comment]
@codecakes The first errors I encountered turned out to be from accidentally closing Docker instead of minimizing the window. 🤦 

I've since run docker-compose up according to the instructions and can see the main splash page at localhost:9119, but I encounter the following when I click on the button to log in or sign up:
<img width="1625" alt="Screen Shot 2021-12-06 at 4 35 25 PM" src="https://user-images.githubusercontent.com/84106309/144918926-5358c15e-6799-4869-b152-19619cffa8fd.png">

Then I thought maybe I was overcomplicating things, and tried `npm start` instead, but got this error message:
<img width="394" alt="Screen Shot 2021-12-06 at 4 35 45 PM" src="https://user-images.githubusercontent.com/84106309/144918995-81fde53c-928a-40f8-9e5c-620f3be02af7.png">

Then I tried `npm install` (figuring that the node_modules were not accessible in the file structure because they were part of the docker container) and got this error message:
<img width="663" alt="Screen Shot 2021-12-06 at 4 43 16 PM" src="https://user-images.githubusercontent.com/84106309/144919711-0a47cffd-cfd8-40c4-991d-85904500493f.png">

I can open an issue, but wanted to check first if you think these look like user error on my end or an actual problem with the docker-compose file or instructions. I haven't run into this many build issues in a long time, but the initial ones were caused by a pretty basic oversight on my part and I'm not having the best day, so maybe I'm missing something else obvious as well.

**Comment by codecakes** [comment]
@jayeclark Feel free to contribute to the actual README documentation instead; relevant ticket is opened here now: https://github.com/Xcov19/mycovidconnect/issues/242

While I've added sparingly the checklist on what would help resolve these issues, they in no way block the development of this feature.

> @codecakes The first errors I encountered turned out to be from accidentally closing Docker instead of minimizing the window. facepalm
> 
> I've since run docker-compose up according to the instructions and can see the main splash page at localhost:9119, but I encounter the following when I click on the button to log in or sign up: <img alt="Screen Shot 2021-12-06 at 4 35 25 PM" width="1625" src="https://user-images.githubusercontent.com/84106309/144918926-5358c15e-6799-4869-b152-19619cffa8fd.png">
> 

Here, you don't need to include this flow and is not part of the scope for this feature request. See details in the issue #242 for why.

> Then I thought maybe I was overcomplicating things, and tried `npm start` instead, but got this error message: <img alt="Screen Shot 2021-12-06 at 4 35 45 PM" width="394" src="https://user-images.githubusercontent.com/84106309/144918995-81fde53c-928a-40f8-9e5c-620f3be02af7.png">
> 

All of this is also documented and suggestions provided in #242 ; Which you can take up at will.

For this particular feature though you were successfully able to run the instance on your local with docker. So the next step I'd suggest is to expose another route for a new page with same header and footer and implement this new form, that's it and you should be able to test it out on your local as well;

The way to move forward would be:

- [ ] Refer to https://github.com/Xcov19/mycovidconnect/issues/233#issuecomment-985918612 and implement a dummy POST form
- [ ] Then test out the request-response here: https://github.com/Xcov19/mycovidconnect/issues/233#issue-1061838285 and implement that;
- [ ] introduce a constant in the constants file with the api uri (you can use dummy api from stoplight.io); In constants file we pickup the actual url from env vars so it's a drop replacement and it should just work!

Thanks!

**Comment by codecakes** [comment]
https://github.com/Xcov19/mycovidconnect/issues/265 duplicates this and is an improvisation on this issue.
It has a readily available custom made form. no backend integration is necessary there. the data is stored in a tabular sheet.
the sheet can then be synced at will or automated to save data via an api call as described here
https://mycovidconnect.stoplight.io/docs/registrations/3bafb969a5011-register-hospital-center
