### ISSUE TITLE
Create a page with new route and drop this embed code in the body 

### ISSUE THREAD

**Issue by codecakes** [Xcov19/mycovidconnect#241]
**Is your feature request related to a problem? Please describe.**
Change the footer link from mailto to a new page. This opens up many interaction channels for users.

**Describe the solution you'd like**
Keeping the same layout with header and footer, create a new body component and drop the following embedded snippet:

```html5
<!-- Start Campsite embed code -->
<iframe id="js-campsite-iframe" src="https://campsite.bio/myhealthconnect?iframe=1" frameborder="0" scrolling="no" width="100%" height="500"></iframe>
<script src="https://cdn.campsite.bio/js/iframe.js" async></script>
<!-- End Campsite embed code -->
```

**Comment by hardco2020** [comment]
@codecakes  Hi, this is my first try at contributing to an open-source project, according to what you mentioned, I forked the project, and added a new page, here's the screenshot, just want to make sure I did everything right before submitting a pull request.

![Contact Page](https://i.imgur.com/fh4QnX9.png)

Footer.jsx

```javascript=
<Link to="/contact"
  href="mailto:reachout@mycovidconnect.com"
  target="_blank"
  rel="noopener noreferrer"
>
Contact Us
</Link>
```

App.jsx
```javascript=
<Route path="/contact" component={Contact} />
````

Contact.js 
```javascript=
import React from 'react'
import MaindHOC from '../components/MainHOC';

const Contact = () => {
    return (
        <div>
             <iframe
                id="js-campsite-iframe"
                src="https://campsite.bio/myhealthconnect?iframe=1"
                frameborder="0"
                scrolling="no"
                width="100%"
                height="500" 
                title='contact-info'          
            ></iframe>
        </div>
    )
}

export default MaindHOC(Contact)
```

If there's anything wrong or what I haven't included, please let me know, If it's all good, I will go ahead and do a pull request, so that you can check on more details.
I am a new contributor and this is my first try, I will really appreciate it if you can let me know there's anything I should look out for! Thanks!

**Comment by codecakes** [comment]
@hardco2020 glad you picked this up! looks about right. Better to raise a PR and we can talk over there. go ahead and create one
